const TempDummyData =[
    {
        id: 1,
        city: "Jeju",
        fullCityName: "대한민국 제주도",
        email: "masilgasil@gmail.com",
        tourName: "Test1",
        tourStartDay: "2023.07.06",
        tourEndDay: "2023.07.10",
        lastUpdateDay: "2023.05.30",
        level: "L",
        selectedLocation: "19",
        img: process.env.PUBLIC_URL + "/images/jeju.jfif",
    },
    {
        id: 2,
        city: "Gangwon",
        fullCityName: "대한민국 강원도",
        email: "silsil115@gmail.com",
        tourName: "Test2",
        tourStartDay: "2023.07.15",
        tourEndDay: "2023.07.20",
        lastUpdateDay: "2023.02.30",
        level: "L",
        selectedLocation: "20",
        img: process.env.PUBLIC_URL + "/images/jeju.jfif",
    },
    {
        id: 3,
        city: "Gwangju",
        fullCityName: "대한민국 광주광역시",
        email: "eysilgasil@gmail.com",
        tourName: "Test3",
        tourStartDay: "2023.08.07",
        tourEndDay: "2023.08.12",
        lastUpdateDay: "2023.03.15",
        level: "L",
        selectedLocation: "21",
        img: process.env.PUBLIC_URL + "/images/jeju.jfif",
    },
    {
        id: 4,
        city: "Busan",
        fullCityName: "대한민국 부산광역시",
        email: "yosilgasil@gmail.com",
        tourName: "Test4",
        tourStartDay: "2023.09.22",
        tourEndDay: "2023.09.28",
        lastUpdateDay: "2023.04.20",
        level: "L",
        selectedLocation: "22",
        img: process.env.PUBLIC_URL + "/images/jeju.jfif",
    },
    {
        id: 5,
        city: "Jeju",
        fullCityName: "대한민국 제주도",
        email: "masilgasil@gmail.com",
        tourName: "Test1",
        tourStartDay: "2023.07.06",
        tourEndDay: "2023.07.10",
        lastUpdateDay: "2023.05.30",
        level: "L",
        selectedLocation: "19",
        img: process.env.PUBLIC_URL + "/images/jeju.jfif",
    },
    {
        id: 6,
        city: "Gangwon",
        fullCityName: "대한민국 강원도",
        email: "silsil115@gmail.com",
        tourName: "Test2",
        tourStartDay: "2023.07.15",
        tourEndDay: "2023.07.20",
        lastUpdateDay: "2023.02.30",
        level: "L",
        selectedLocation: "20",
        img: process.env.PUBLIC_URL + "/images/jeju.jfif",
    },
    {
        id: 7,
        city: "Gwangju",
        fullCityName: "대한민국 광주광역시",
        email: "eysilgasil@gmail.com",
        tourName: "Test3",
        tourStartDay: "2023.08.07",
        tourEndDay: "2023.08.12",
        lastUpdateDay: "2023.03.15",
        level: "L",
        selectedLocation: "21",
        img: process.env.PUBLIC_URL + "/images/jeju.jfif",
    },
    {
        id: 8,
        city: "Busan",
        fullCityName: "대한민국 부산광역시",
        email: "yosilgasil@gmail.com",
        tourName: "Test4",
        tourStartDay: "2023.09.22",
        tourEndDay: "2023.09.28",
        lastUpdateDay: "2023.04.20",
        level: "L",
        selectedLocation: "22",
        img: process.env.PUBLIC_URL + "/images/jeju.jfif",
    },
    {
        id: 9,
        city: "Jeju",
        fullCityName: "대한민국 제주도",
        email: "masilgasil@gmail.com",
        tourName: "Test1",
        tourStartDay: "2023.07.06",
        tourEndDay: "2023.07.10",
        lastUpdateDay: "2023.05.30",
        level: "L",
        selectedLocation: "19",
        img: process.env.PUBLIC_URL + "/images/jeju.jfif",
    },
    {
        id: 10,
        city: "Gangwon",
        fullCityName: "대한민국 강원도",
        email: "silsil115@gmail.com",
        tourName: "Test2",
        tourStartDay: "2023.07.15",
        tourEndDay: "2023.07.20",
        lastUpdateDay: "2023.02.30",
        level: "L",
        selectedLocation: "20",
        img: process.env.PUBLIC_URL + "/images/jeju.jfif",
    },
    {
        id: 11,
        city: "Gwangju",
        fullCityName: "대한민국 광주광역시",
        email: "eysilgasil@gmail.com",
        tourName: "Test3",
        tourStartDay: "2023.08.07",
        tourEndDay: "2023.08.12",
        lastUpdateDay: "2023.03.15",
        level: "L",
        selectedLocation: "21",
        img: process.env.PUBLIC_URL + "/images/jeju.jfif",
    },
    {
        id: 12,
        city: "Busan",
        fullCityName: "대한민국 부산광역시",
        email: "yosilgasil@gmail.com",
        tourName: "Test4",
        tourStartDay: "2023.09.22",
        tourEndDay: "2023.09.28",
        lastUpdateDay: "2023.04.20",
        level: "L",
        selectedLocation: "22",
        img: process.env.PUBLIC_URL + "/images/jeju.jfif",
    },

];

export default TempDummyData;