const BusTerminalData = [
    { id: 1, location: "서울2", eng: "NAARKS", kor: "인천, 김포 버스 터미널" },
    { id: 2, location: "제주2", eng: "NAARKPC", kor: "제주국제공항" },
    { id: 3, location: "부산2", eng: "NAARKPK", kor: "김해국제공항" },
    { id: 4, location: "김포2", eng: "NAARKSS", kor: "김포국제공항" },
    { id: 5, location: "인천2", eng: "NAARKSI", kor: "인천국제공항" },
    { id: 6, location: "광주2", eng: "NAARKJJ", kor: "광주공항" },
    { id: 7, location: "무안2", eng: "NAARKJB", kor: "무안국제공항" },
    { id: 8, location: "군산2", eng: "KNAARKJK", kor: "군산공항" },
    { id: 9, location: "대구2", eng: "NAARKTN", kor: "대구국제공항" },
    { id: 10, location: "사천2", eng: "NAARKPS", kor: "사천 버스 터미널" },
    { id: 11, location: "천안어딘가", eng: "NAARKPS", kor: "사천 버스 터미널" },
    { id: 12, location: "천안어딘가", eng: "NAARKPS", kor: "사천 버스 터미널" },
    { id: 13, location: "천안어딘가", eng: "NAARKPS", kor: "사천 버스 터미널" },
    { id: 14, location: "천안어딘가", eng: "NAARKPS", kor: "사천 버스 터미널" },
    { id: 15, location: "천안어딘가", eng: "NAARKPS", kor: "사천 버스 터미널" },
    { id: 16, location: "천안어딘가", eng: "NAARKPS", kor: "사천 버스 터미널" },
    { id: 17, location: "천안어딘가", eng: "NAARKPS", kor: "사천 버스 터미널" },
    { id: 18, location: "천안어딘가", eng: "NAARKPS", kor: "사천 버스 터미널" },
    { id: 19, location: "천안어딘가", eng: "NAARKPS", kor: "사천 버스 터미널" },
    { id: 20, location: "천안어딘가", eng: "NAARKPS", kor: "사천 버스 터미널" },
    { id: 21, location: "천안어딘가", eng: "NAARKPS", kor: "사천 버스 터미널" },
    { id: 22, location: "천안어딘가", eng: "NAARKPS", kor: "사천 버스 터미널" },
    { id: 23, location: "천안어딘가", eng: "NAARKPS", kor: "사천 버스 터미널" },
    { id: 24, location: "천안어딘가", eng: "NAARKPS", kor: "사천 버스 터미널" },
    { id: 25, location: "천안어딘가", eng: "NAARKPS", kor: "사천 버스 터미널" },
    { id: 26, location: "천안어딘가1", eng: "NAARKPS", kor: "사천 버스 터미널" },
    { id: 27, location: "천안어딘가2", eng: "NAARKPS", kor: "사천 버스 터미널" },
    { id: 28, location: "천안어딘가3", eng: "NAARKPS", kor: "사천 버스 터미널" },
    { id: 29, location: "천안어딘가4", eng: "NAARKPS", kor: "사천 버스 터미널" },
];

export default BusTerminalData;
